"""Add requests table

Revision ID: 12ac07208747
Revises: 72616e239316
Create Date: 2026-02-10 10:00:26.299960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ac07208747'
down_revision: Union[str, None] = '72616e239316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('catalog_item', sa.String(length=100), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_for_id', sa.UUID(), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('assigned_group_id', sa.UUID(), nullable=True),
    sa.Column('fulfilled_by_id', sa.UUID(), nullable=True),
    sa.Column('fulfilled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfillment_notes', sa.Text(), nullable=True),
    sa.Column('closed_by_id', sa.UUID(), nullable=True),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_notes', sa.Text(), nullable=True),
    sa.Column('sla_target_fulfill', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breach', sa.String(length=20), nullable=True),
    sa.Column('fulfillment_time_minutes', sa.Integer(), nullable=True),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('estimated_cost', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_for_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_assigned_to_id'), 'requests', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_requests_category'), 'requests', ['category'], unique=False)
    op.create_index(op.f('ix_requests_company_id'), 'requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_requests_priority'), 'requests', ['priority'], unique=False)
    op.create_index(op.f('ix_requests_request_number'), 'requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_requests_requested_by_id'), 'requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_tenant_id'), 'requests', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_tenant_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_requested_by_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_request_number'), table_name='requests')
    op.drop_index(op.f('ix_requests_priority'), table_name='requests')
    op.drop_index(op.f('ix_requests_company_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_category'), table_name='requests')
    op.drop_index(op.f('ix_requests_assigned_to_id'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
