"""add_metadata_tables

Revision ID: 132be1c6d429
Revises: 822e3140f624
Create Date: 2026-02-11 21:51:00.084501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '132be1c6d429'
down_revision: Union[str, None] = '822e3140f624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_choice',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('sys_class_name', sa.String(length=50), nullable=True),
    sa.Column('dependent_field', sa.String(length=100), nullable=True),
    sa.Column('dependent_value', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sys_choice_lookup', 'sys_choice', ['tenant_id', 'table_name', 'field_name', 'sys_class_name'], unique=False)
    op.create_index(op.f('ix_sys_choice_tenant_id'), 'sys_choice', ['tenant_id'], unique=False)
    op.create_table('sys_db_object',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('plural_label', sa.String(length=255), nullable=True),
    sa.Column('super_class', sa.String(length=100), nullable=True),
    sa.Column('display_field', sa.String(length=100), nullable=True),
    sa.Column('number_prefix', sa.String(length=10), nullable=True),
    sa.Column('is_extendable', sa.Boolean(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sys_db_object_tenant_name', 'sys_db_object', ['tenant_id', 'name'], unique=True)
    op.create_index(op.f('ix_sys_db_object_tenant_id'), 'sys_db_object', ['tenant_id'], unique=False)
    op.create_table('sys_dictionary',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('is_display', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('reference_table', sa.String(length=100), nullable=True),
    sa.Column('reference_display_field', sa.String(length=100), nullable=True),
    sa.Column('hint', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('sys_class_name', sa.String(length=50), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('column_exists', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sys_dict_lookup', 'sys_dictionary', ['tenant_id', 'table_name', 'column_name', 'sys_class_name'], unique=False)
    op.create_index('idx_sys_dict_table', 'sys_dictionary', ['tenant_id', 'table_name'], unique=False)
    op.create_index(op.f('ix_sys_dictionary_tenant_id'), 'sys_dictionary', ['tenant_id'], unique=False)
    op.create_table('sys_relationship',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_table', sa.String(length=100), nullable=False),
    sa.Column('child_table', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('foreign_key_field', sa.String(length=100), nullable=True),
    sa.Column('join_table', sa.String(length=100), nullable=True),
    sa.Column('join_parent_field', sa.String(length=100), nullable=True),
    sa.Column('join_child_field', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sys_rel_parent_child', 'sys_relationship', ['tenant_id', 'parent_table', 'child_table'], unique=False)
    op.create_index(op.f('ix_sys_relationship_tenant_id'), 'sys_relationship', ['tenant_id'], unique=False)
    op.create_table('sys_ui_view',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('sys_class_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sys_ui_view_lookup', 'sys_ui_view', ['tenant_id', 'table_name', 'name', 'sys_class_name'], unique=True)
    op.create_index(op.f('ix_sys_ui_view_tenant_id'), 'sys_ui_view', ['tenant_id'], unique=False)
    op.create_table('sys_ui_list',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('view_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('sort_direction', sa.String(length=4), nullable=True),
    sa.Column('sort_priority', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['sys_ui_view.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_ui_list_tenant_id'), 'sys_ui_list', ['tenant_id'], unique=False)
    op.create_table('sys_ui_related_list',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('view_id', sa.UUID(), nullable=False),
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('display_fields', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_condition', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('max_rows', sa.Integer(), nullable=False),
    sa.Column('sys_class_name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['relationship_id'], ['sys_relationship.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['sys_ui_view.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_ui_related_list_tenant_id'), 'sys_ui_related_list', ['tenant_id'], unique=False)
    op.create_table('sys_ui_section',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('view_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('section_type', sa.String(length=30), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_expanded', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('sys_class_name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['sys_ui_view.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_ui_section_tenant_id'), 'sys_ui_section', ['tenant_id'], unique=False)
    op.create_table('sys_ui_element',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('element_type', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('column_index', sa.Integer(), nullable=False),
    sa.Column('annotation_text', sa.Text(), nullable=True),
    sa.Column('span', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sys_ui_section.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_ui_element_tenant_id'), 'sys_ui_element', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_ui_element_tenant_id'), table_name='sys_ui_element')
    op.drop_table('sys_ui_element')
    op.drop_index(op.f('ix_sys_ui_section_tenant_id'), table_name='sys_ui_section')
    op.drop_table('sys_ui_section')
    op.drop_index(op.f('ix_sys_ui_related_list_tenant_id'), table_name='sys_ui_related_list')
    op.drop_table('sys_ui_related_list')
    op.drop_index(op.f('ix_sys_ui_list_tenant_id'), table_name='sys_ui_list')
    op.drop_table('sys_ui_list')
    op.drop_index(op.f('ix_sys_ui_view_tenant_id'), table_name='sys_ui_view')
    op.drop_index('idx_sys_ui_view_lookup', table_name='sys_ui_view')
    op.drop_table('sys_ui_view')
    op.drop_index(op.f('ix_sys_relationship_tenant_id'), table_name='sys_relationship')
    op.drop_index('idx_sys_rel_parent_child', table_name='sys_relationship')
    op.drop_table('sys_relationship')
    op.drop_index(op.f('ix_sys_dictionary_tenant_id'), table_name='sys_dictionary')
    op.drop_index('idx_sys_dict_table', table_name='sys_dictionary')
    op.drop_index('idx_sys_dict_lookup', table_name='sys_dictionary')
    op.drop_table('sys_dictionary')
    op.drop_index(op.f('ix_sys_db_object_tenant_id'), table_name='sys_db_object')
    op.drop_index('idx_sys_db_object_tenant_name', table_name='sys_db_object')
    op.drop_table('sys_db_object')
    op.drop_index(op.f('ix_sys_choice_tenant_id'), table_name='sys_choice')
    op.drop_index('idx_sys_choice_lookup', table_name='sys_choice')
    op.drop_table('sys_choice')
    # ### end Alembic commands ###
