"""add_client_scripts_table

Revision ID: 822e3140f624
Revises: 104ae57f8491
Create Date: 2026-02-11 19:34:10.926319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '822e3140f624'
down_revision: Union[str, None] = '104ae57f8491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_scripts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('sys_class_name', sa.String(length=50), nullable=True),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('trigger_field', sa.String(length=100), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('condition_logic', sa.String(length=10), nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ui_actions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_scripts_tenant_table_event', 'client_scripts', ['tenant_id', 'table_name', 'event'], unique=False)
    op.create_index(op.f('ix_client_scripts_tenant_id'), 'client_scripts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_scripts_tenant_id'), table_name='client_scripts')
    op.drop_index('idx_client_scripts_tenant_table_event', table_name='client_scripts')
    op.drop_table('client_scripts')
    # ### end Alembic commands ###
