"""Add incident user fields (opened_by, caller, affected_user) and support_group FK

Revision ID: a12adab4151a
Revises: 7e8f9a0b13c2
Create Date: 2026-02-10 15:50:33.123876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12adab4151a'
down_revision: Union[str, None] = '7e8f9a0b13c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add opened_by_id as nullable first (for existing rows)
    op.add_column('incidents', sa.Column('opened_by_id', sa.UUID(), nullable=True))

    # Step 2: Copy reported_by_id to opened_by_id for existing incidents
    op.execute('UPDATE incidents SET opened_by_id = reported_by_id WHERE opened_by_id IS NULL')

    # Step 3: Make opened_by_id NOT NULL
    op.alter_column('incidents', 'opened_by_id', nullable=False)

    # Add other nullable fields
    op.add_column('incidents', sa.Column('caller_id', sa.UUID(), nullable=True))
    op.add_column('incidents', sa.Column('affected_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_incidents_affected_user_id'), 'incidents', ['affected_user_id'], unique=False)
    op.create_index(op.f('ix_incidents_assigned_group_id'), 'incidents', ['assigned_group_id'], unique=False)
    op.create_index(op.f('ix_incidents_caller_id'), 'incidents', ['caller_id'], unique=False)
    op.create_index(op.f('ix_incidents_opened_by_id'), 'incidents', ['opened_by_id'], unique=False)
    op.create_foreign_key(None, 'incidents', 'users', ['opened_by_id'], ['id'])
    op.create_foreign_key(None, 'incidents', 'support_groups', ['assigned_group_id'], ['id'])
    op.create_foreign_key(None, 'incidents', 'users', ['affected_user_id'], ['id'])
    op.create_foreign_key(None, 'incidents', 'users', ['caller_id'], ['id'])
    op.drop_index('ix_permission_group_members_group', table_name='permission_group_members')
    op.drop_index('ix_permission_group_members_user', table_name='permission_group_members')
    op.drop_constraint('uq_permission_group_user', 'permission_group_members', type_='unique')
    op.drop_index('ix_permission_group_roles_group', table_name='permission_group_roles')
    op.drop_index('ix_permission_group_roles_role', table_name='permission_group_roles')
    op.drop_constraint('uq_permission_group_role', 'permission_group_roles', type_='unique')
    op.drop_index('ix_roles_code', table_name='roles')
    op.drop_index('ix_roles_module', table_name='roles')
    op.drop_constraint('uq_users_user_id', 'users', type_='unique')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_unique_constraint('uq_users_user_id', 'users', ['user_id'])
    op.create_index('ix_roles_module', 'roles', ['module'], unique=False)
    op.create_index('ix_roles_code', 'roles', ['code'], unique=False)
    op.create_unique_constraint('uq_permission_group_role', 'permission_group_roles', ['permission_group_id', 'role_id'])
    op.create_index('ix_permission_group_roles_role', 'permission_group_roles', ['role_id'], unique=False)
    op.create_index('ix_permission_group_roles_group', 'permission_group_roles', ['permission_group_id'], unique=False)
    op.create_unique_constraint('uq_permission_group_user', 'permission_group_members', ['permission_group_id', 'user_id'])
    op.create_index('ix_permission_group_members_user', 'permission_group_members', ['user_id'], unique=False)
    op.create_index('ix_permission_group_members_group', 'permission_group_members', ['permission_group_id'], unique=False)
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_opened_by_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_caller_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_group_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_affected_user_id'), table_name='incidents')
    op.drop_column('incidents', 'affected_user_id')
    op.drop_column('incidents', 'caller_id')
    op.drop_column('incidents', 'opened_by_id')
    # ### end Alembic commands ###
