"""Add tasks table - central ticket system

Revision ID: e5b6eb413529
Revises: a12adab4151a
Create Date: 2026-02-10 16:30:02.623131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5b6eb413529'
down_revision: Union[str, None] = 'a12adab4151a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sys_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('sys_class_name', sa.String(length=50), nullable=False),
    sa.Column('sys_created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sys_updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('opened_by_id', sa.UUID(), nullable=False),
    sa.Column('caller_id', sa.UUID(), nullable=True),
    sa.Column('caller_company_id', sa.UUID(), nullable=True),
    sa.Column('affected_user_id', sa.UUID(), nullable=True),
    sa.Column('affected_user_company_id', sa.UUID(), nullable=True),
    sa.Column('assignment_group_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('reassignment_count', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_reason', sa.String(length=100), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_reason', sa.String(length=100), nullable=True),
    sa.Column('close_notes', sa.Text(), nullable=True),
    sa.Column('closed_by_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_target_respond', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_target_resolve', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breach', sa.Boolean(), nullable=True),
    sa.Column('response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=True),
    sa.Column('last_modified_by_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('affected_services', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_users_count', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('related_task_id', sa.UUID(), nullable=True),
    sa.Column('external_ticket_id', sa.String(length=100), nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affected_user_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['affected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['support_groups.id'], ),
    sa.ForeignKeyConstraint(['caller_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.sys_id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sys_id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('idx_tasks_assigned_to', 'tasks', ['assigned_to_id'], unique=False)
    op.create_index('idx_tasks_assignment_group', 'tasks', ['assignment_group_id'], unique=False)
    op.create_index('idx_tasks_company', 'tasks', ['company_id'], unique=False)
    op.create_index('idx_tasks_created', 'tasks', ['sys_created_on'], unique=False)
    op.create_index('idx_tasks_number', 'tasks', ['number'], unique=False)
    op.create_index('idx_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_tenant_class', 'tasks', ['tenant_id', 'sys_class_name'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tasks_assignment_group_id'), 'tasks', ['assignment_group_id'], unique=False)
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_tasks_impact'), 'tasks', ['impact'], unique=False)
    op.create_index(op.f('ix_tasks_number'), 'tasks', ['number'], unique=True)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_sys_class_name'), 'tasks', ['sys_class_name'], unique=False)
    op.create_index(op.f('ix_tasks_sys_id'), 'tasks', ['sys_id'], unique=True)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tasks_urgency'), 'tasks', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_urgency'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_sys_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_sys_class_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_number'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_impact'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignment_group_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_index('idx_tasks_tenant_class', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_priority', table_name='tasks')
    op.drop_index('idx_tasks_number', table_name='tasks')
    op.drop_index('idx_tasks_created', table_name='tasks')
    op.drop_index('idx_tasks_company', table_name='tasks')
    op.drop_index('idx_tasks_assignment_group', table_name='tasks')
    op.drop_index('idx_tasks_assigned_to', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
