"""add_server_scripts_table

Revision ID: fdeb64d4a1d4
Revises: a786249c42fb
Create Date: 2026-02-11 16:27:17.842852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdeb64d4a1d4'
down_revision: Union[str, None] = 'a786249c42fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_scripts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('sys_class_name', sa.String(length=50), nullable=True),
    sa.Column('timing', sa.String(length=30), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_scripts_tenant_table_timing', 'server_scripts', ['tenant_id', 'table_name', 'timing'], unique=False)
    op.create_index(op.f('ix_server_scripts_tenant_id'), 'server_scripts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_scripts_tenant_id'), table_name='server_scripts')
    op.drop_index('idx_server_scripts_tenant_table_timing', table_name='server_scripts')
    op.drop_table('server_scripts')
    # ### end Alembic commands ###
